name: siwa
description: sign in with apple. Apple login plugin for three-party login.
version: 0.1.2
homepage: https://github.com/jeromexiong/flutter-siwa

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      # android:
      #   package: cc.dync.siwa
      #   pluginClass: SiwaPlugin
      ios:
        pluginClass: SiwaPlugin
